Draft parte 3
elagarrigue/AyDS21-AK-Apolo3 pull request #2
Opened 2021-05-14 15:51 UTC by ngeoffroy

2021-05-18 18:42 UTC, elagarrigue requested changes
- Falta descripción del PR

2021-05-18 18:42 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistTablesCreate.kt
> +class ArtistTablesCreate(context: Context?) : SQLiteOpenHelper(context, "dictionary.db", null, 1) {
- El parámetro context no debería ser nullable
- Definir constantes para el nombre de la db y el número de versión

2021-05-18 18:42 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistTablesCreate.kt
> +    private val databaseToRead = this.readableDatabase
estas propiedades no aportan nada, se pueden evitar y hacer inline

2021-05-18 18:42 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistTablesCreate.kt
> +    }
Acá hay un smell de efecto secundario. El método modifica un parámetro. No es necesario, mejor evitar el parámetro databaseNewColumn y retornar el objeto ContentValues.

2021-05-18 18:42 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistTablesCreate.kt
> +        }
Se puede simplificar 
```suggestion
        return items.firstOrNull()
```

2021-05-18 18:42 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoWindowActivity.kt
> +        getArtistInfo(intent.getStringExtra(ARTIST_NAME))
distinto nivel de abstracción

2021-05-18 18:42 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoWindowActivity.kt
> +        }
Hace 3 cosas: obtener la referencia a la vista (deberia estar en init), setear el listener (no deberia ser responsabilidad de `setURLButtonListener(url: JsonElement)`, y disparar otra actividad

2021-05-18 18:42 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoWindowActivity.kt
> +        return infoFromJsonBioContentAndUrl
distinto nivel de abstracción

2021-05-18 18:42 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoWindowActivity.kt
> +            .create(LastFMAPI::class.java)
distinto nivel de abstracción y constante, mover a una propiedad

2021-05-18 18:42 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoWindowActivity.kt
> +        }.start()
Hace muchas cosas...

2021-05-19 22:14 UTC, elagarrigue requested changes
Falta descripcion del PR

2021-05-19 22:14 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoWindowActivity.kt
> +
No esta bien el formato, auto indentar líneas

2021-05-19 22:14 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoWindowActivity.kt
> +    }
- El nombre de la función no revela intención
- No está bien indentado
- Hace muchas cosas, inicializar el thread, parte de la lógica de repository, actualizar la ui
-  writeArtistInDatabase(lastFMAPI,artistName!!): se le pasa la api por parámetro? Tiene como efecto secundario traer los datos del servicio...

2021-05-19 22:14 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoWindowActivity.kt
> +            .into(findViewById<View>(R.id.imageView) as ImageView)
- `findViewById<View>(R.id.imageView) as ImageView ` no es el mismo nivel de abstracción, crear una propiedad como ocn las otras views

2021-05-19 22:14 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoWindowActivity.kt
> +        moreDetailsPane.text = Html.fromHtml(resultArtistFromDatabase)
otro nivel de abstracción, y dentro de `initApiImage` ?

2021-05-19 22:14 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoWindowActivity.kt
> +        return dataBase.getInfo(artistName!!)
`!!` es siempre un smell. Evitar haciendo el parámetro no nullable

2021-05-19 22:14 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoWindowActivity.kt
> +        initURLButtonListener(contentAndUrl[1])
- setear un listener en este punto es un smell, debería setearse en la inicialización 
- `contentAndUrl`, un array no es el mejor tipo de retorno. Claramente indica que hace dos cosas...

2021-05-19 22:14 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoWindowActivity.kt
> +        dataBase.saveArtist(artistName!!, assignArtistContent)
!! innecesario

2021-05-19 22:14 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/OtherInfoWindowActivity.kt
> +    private fun formatText(term: String?, text: String): String {
evitar el nullable

2021-05-22 18:46 UTC, elagarrigue requested changes
- Sigue faltando la descripción del PR

2021-05-22 18:46 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistActivity.kt
> +    private fun runUiThread() {
no es un nombre que declare intención

2021-05-22 18:46 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistActivity.kt
> +    private fun plusStoreLetter(): String = STORE_LETTER.plus(resultArtistFromDatabase)
no es un nombre claro, mejor `addStorePrefix` o algo así

2021-05-22 18:46 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistActivity.kt
> +        moreDetailsPane.text = Html.fromHtml(resultArtistFromDatabase)
- `initApiImage` no es un bueno nombre. No es exactamente lo que hace, usa el nombre `api` que es detalle de implementación, y el método en sí hace dos cosas.
- Las dos cosas que hace no corresponden al mismo nivel de abstracción.
- El nombre del parámetro describe un detalle que no es relevante para la función (from database)

2021-05-22 18:46 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistActivity.kt
> +        }
`when` innecesario...

2021-05-22 18:46 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistActivity.kt
> +    private fun checkArtistInDatabase() {
no es un nombre correcto. Aquí deberíamos tener la lógica del repository, mejor `updateArtistInfo()`

2021-05-22 18:46 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistActivity.kt
> +                null -> writeArtistInDatabase()
`writeArtistInDataBase` tiene como efecto secundario obtener los datos del servicio externo. Ver la implementación del repositorio en home para tener de referencia.

2021-05-22 21:22 UTC, ngeoffroy commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistActivity.kt
> +                null -> writeArtistInDatabase()
Hola Ema! Cuando te referís a que trae datos del servicio externo, te referís a que está haciendo múltiples tareas, no? Es decir, guardando dentro de la BD y asignando un resultado a la variable resultArtistFromDatabase?

2021-05-23 18:23 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistActivity.kt
> +                null -> writeArtistInDatabase()
Haciendo multiples tareas, sí. Trayendo el dato del servicio externo (no relacionado con la base de datos), y guardando el resultado en la dB.

2021-05-23 18:27 UTC, elagarrigue requested changes
Últimos nombres a cambiar

2021-05-23 18:27 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistActivity.kt
> +    private fun initArtistUI() {
mejor `updateArtistInfoUI()`

2021-05-23 18:27 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistActivity.kt
> +            resultArtistFromDatabase=artistToHTML()
- `resultArtistFromDatabase` no es un bueno nombre, en este caso no proviene de la db, sino del servicio externo.
 -  `artistToHTML` no es un buen nombre, trae los datos del servicio externo. Comparar con la implementación del reposotorio en home.
 - La clase no esta bien indentada, no hay espacios entre el `=` de la asignación.

2021-05-23 20:36 UTC, SaintRoguer commented
Modificado nombres de variables y metodos.
initArtistUI() -> updateArtistInfoUI()
resultArtistFromDatabase -> resultArtistFromFMApi
artistToHTML() -> fmApiInfoToHTML()
Arreglada la identacion de la linea 117

2021-05-24 12:39 UTC, elagarrigue requested changes

2021-05-24 12:39 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistActivity.kt
> +    private var resultArtistFromFMApi: String? = null
```suggestion
    private var artistInfo: String? = null
```

2021-05-24 12:39 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/fulllogic/ArtistActivity.kt
> +    private fun fmApiInfoToHTML(): String {
```suggestion
    private fun getArtistInfoFromLastFM(): String {
```

2021-05-24 12:44 UTC, SaintRoguer commented
modificado nombre de variable y metodo
resultArtistFromFMApi -> artistInfo
fmApiInfoToHTML() -> getArtistInfoFromLastFM()

2021-05-24 13:11 UTC, elagarrigue approved these changes

2021-05-24 13:11 UTC, merged