Parte 4
elagarrigue/AyDS21-AK-Apolo3 pull request #3
Opened 2021-05-29 15:48 UTC by JavierTierno

Hola Emma, queríamos saber si lo que venimos haciendo esta correcto! El ultimo commit realizado fue resuelto en grupo con los 4 integrantes para terminar de formar el patrón MVC. 

Saludos, 
El equipo de Apolo 3

2021-06-03 00:46 UTC, ngeoffroy commented
Hola Ema y Ariana!
Ahi hicimos andar la aplicación, pero tenemos un problemita en la ventana del more details. El programa muestra correctamente la información de la banda, pero concatena una parte que no debería estar ahí. Adjunto en el comentario una screen para verlo en más detalle.
También, incluímos el diagrama de clases reducido por si hay que corregir cosas.

Desde ya muchisimas gracias, y perdon por molestarlos!!
![Sin título](https://user-images.githubusercontent.com/81689515/120569265-f0d2a680-c3eb-11eb-9142-7d9e81f49027.png)

2021-06-03 12:48 UTC, elagarrigue reviewed
El string final en la descripción es parte del resultado, no hace falta sacarlo.
Con respecto al diagrama:
- Falta englobar las clases en los paquetes
- Dejen sólo las interfaces (si en calificador <<interface>>). La idea es transmitir estructura general, no detalle de implementación.

2021-06-06 13:32 UTC, elagarrigue requested changes
- Actualizar la descripción del PR
- Diagrama:
   - Englobar en el paquete more details
   - Agregar los sub paquetes
   - Si la relación es entre paquetes, relacionar paquete a paquete (no clase a clase)
   - Agregar las relaciones indirectas (por los observers)
   - Agregar home (sin detalle)

2021-06-06 13:32 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/MoreDetailsModel.kt
> +        repository.getArticleByArtistName(artistName)
View Full Article debería abrir la url en un browser...

2021-06-06 13:32 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/entities/ArtistArticle.kt
> +    val artistName: String
No debería ser parte de Article

2021-06-06 13:32 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/local/lastfm/sqldb/ArtistLocalStorageImpl.kt
> +        put(INFO_COLUMN, artistInfo[1])
Englobar parámetros en un array es un smell, es poco legible (hay q hacer mapeo mental, ir al lugar donde se llama a la función para ver qué significa cada posición. Mejor, mandar la lista de parámetros.

2021-06-06 13:32 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/MoreDetailsModel.kt
> +    fun viewFullArticle(artistName: String): Article
Este método no debería estar acá, `view` no es de modelo

2021-06-06 13:32 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/view/ArticleHelper.kt
> +interface ArticleHelper {
El nombre es poco declarativo, no revela intención.

2021-06-06 13:32 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/view/MoreDetailsView.kt
> +    private val helperArticleInfo: ArticleHelper = MoreDetailsViewModule.helperArticleInfo
Estas propiedades redireccionan la instancia nomás, no suman valor. Si podemos eliminar propiedades, mejor

2021-06-06 13:32 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/view/MoreDetailsView.kt
> +            openURLActivity()
`openURLActivity` no es responsabilidad de la vista, debería dispararlo el controlador

2021-06-06 13:32 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/view/MoreDetailsView.kt
> +            else -> withoutPrefix(article)
Estos nombres no revelan intención. Mejor:
- `updateStoredArticleUiState`
- `updateNewArticleUiState`

2021-06-06 13:32 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/view/MoreDetailsView.kt
> +            }"
Eliminar logs extra

2021-06-06 13:32 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/utils/view/ImageLoader.kt
> +import android.util.Log
Revertir

2021-06-06 13:32 UTC, elagarrigue commented on AK Apolo/build.gradle
> +        classpath 'com.android.tools.build:gradle:4.2.1'
Actualizar las librerías puede ser peligroso, pueden no ser compatibles hacia atrás. Revertir, por scope del PR

2021-06-06 14:53 UTC, JavierTierno commented
> * Actualizar la descripción del PR
> * Diagrama:
>   
>   * Englobar en el paquete more details
>   * Agregar los sub paquetes
>   * Si la relación es entre paquetes, relacionar paquete a paquete (no clase a clase)
>   * Agregar las relaciones indirectas (por los observers)
>   * Agregar home (sin detalle)

Dudas:
El segundo ítem se refiere a agregar los sub paquetes como entities, repository, external e internal dentro de Model en el diagrama?
También debo agregar al diagrama el paquete Utils?

2021-06-08 12:31 UTC, elagarrigue requested changes
Diagrama de clases:
- Achicar los nombres de los paquetes y sacarlos de los cuadros amarillos, es un poco confuso (parecen clases).
-  Usar los nombres de los paquetes reales, en lower case
- Que las flechas no crucen los paquetes
- La relación del observer de controller a view es a la inversa 
- Falta la relación indirecta model -> view

2021-06-08 12:31 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/view/MoreDetailsViewModule.kt
> +    val HELPER_ARTICLE_INFO: ArticleFormatter = ArticleFormatterImpl()
propiedades siempre en camelCase

2021-06-08 12:31 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/view/MoreDetailsView.kt
> +            MoreDetailsViewModule.HELPER_ARTICLE_INFO.getTextToHtml(uiState.artistInfo, uiState.artistName)
Inyectar la dependencia

2021-06-08 12:31 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/view/MoreDetailsView.kt
> +            artistInfo = ""
Si no hay resultados no se muestra nada? Probar yendo a more details sin conexión

2021-06-08 12:31 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/ArticleRepository.kt
> +        addStorePrefix(artistArticle)
Esta línea no hace nada

2021-06-08 12:31 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/ArticleRepository.kt
> +        STORE_LETTER.plus(artistArticle)
Lógica de view

2021-06-08 16:32 UTC, elagarrigue requested changes
Últimos detalles

2021-06-08 16:32 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/ArticleRepository.kt
> +const val STORE_LETTER = "*"
Dead code

2021-06-08 16:32 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/ArticleRepository.kt
> +            artistArticle != null -> artistArticle.isLocallyStoraged = true
`artistArticle.isLocallyStoraged = true` no es el mismo nivel de abstracción, moverlo a una sub función.

2021-06-08 16:32 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/view/MoreDetailsView.kt
> +            articleURL = "Artículo no encontrado!",
No es una url, dejar vacío

2021-06-09 12:31 UTC, elagarrigue approved these changes
Ahí quedó bien 👍🏽 . Recuerden para la próxima actualizar la descripción del PR.

2021-06-09 12:31 UTC, merged