Parte 5 - Submodule
elagarrigue/AyDS21-AK-Apolo3 pull request #4
Opened 2021-06-16 19:40 UTC by JavierTierno

Exportado el servicio de LastFM del modulo moredetails y creado el submódulo correspondiente.
Modificamos la entidad ArtistArticle y la reemplazamos por una nueva llamada Card.
Realizamos los refactors correspondientes a las clases para que queden acorde a la nueva entidad.
Actualizado el diagrama de clases acorde a los cambios hechos.
Creado el archivo README en el nuevo repositorio donde se ubica dicho submódulo.

Link al repositorio del submódulo:
https://github.com/LPacione/AK-Apolo3-LastFMData

2021-06-17 15:08 UTC, elagarrigue reviewed
- Quedan nombres "Article" cuando debería ser  "Card"

Submodule:
- El el readme del repo no dice cómo obtener la instancia de lastFMInfoService
- En LastFMInfoService quedó `@Query("artist")`, que es un tag de retrofit que no tiene que estar ahí
- Todo dentro del paquete `info` debería ser internal, que no pueda accederse desde afuera del módulo.

2021-06-17 15:08 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/local/sqldb/CardTableConstants.kt
>  const val ARTIST_DESC_COLUMN = "artist DESC"
CARD DESC

2021-06-18 15:46 UTC, JavierTierno commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/local/sqldb/CardTableConstants.kt
>  const val ARTIST_DESC_COLUMN = "artist DESC"
Una pregunta Emma, esta corrección es correcta? Ya que en esa constante estamos refiriéndonos a los artistas y no a los artículos. 
Saludos

2021-06-18 16:32 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/repository/local/sqldb/CardTableConstants.kt
>  const val ARTIST_DESC_COLUMN = "artist DESC"
No, pq en realidad lo que se guarda en esa columna es lo que se trae del servicio. Los artículos de wikipedia por ejemplo, el contenido no es la descripción del artista en sí, sino lo que venga.

2021-06-22 14:36 UTC, elagarrigue reviewed
Me faltó hacer el finish review ayer. Vuelvan a hacer el request review cuando estén listos

2021-06-22 21:22 UTC, elagarrigue requested changes
Últimos detalles

Submodule:

Hay un smell en `getInfoFromExternalData` :
```
 override fun getInfoFromExternalData(serviceData: String?): Article? =
        try {
            serviceData?.getJson()?.getArtistInfo()?.let { item ->
                ArtistArticle(
                    item.getArticleDescription().asString.replace("\\n", "\n"),
                    item.getArticleUrl(), sourceLogoURL()
                )
            }
        } catch (e: Exception) {
            EmptyArticle
        }
```
Si no ocurre una excepción y no se encuentra resultado retorna null, si ocurre una excepción retorna EmtpyArticle. Elijan una de ambas opciones y actualicen la implementación acorde.

2021-06-22 21:22 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/view/MoreDetailsUiState.kt
>      val articleURL: String = "",
cardUrl

2021-06-22 21:22 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/model/entities/Source.kt
> +enum class Source(s: String) {
`s` no es un buen nombre de propiedad

2021-06-23 12:31 UTC, elagarrigue requested changes
último cambio:

En el submodule quedó:
```
fun getInfoFromExternalData(serviceData: String?): Article?
```

Pero con el último cambio ya no devuelven null. Cambiar por:
```
fun getInfoFromExternalData(serviceData: String?): Article
```

2021-06-23 15:19 UTC, elagarrigue requested changes
Les faltó cambiar el tipo not nullable en la interfaz :)

2021-06-23 15:33 UTC, elagarrigue approved these changes
Ahí quedó perfecto 🙌🏽

2021-06-23 15:33 UTC, merged