Parte 6 - Broker and Proxy
elagarrigue/AyDS21-AK-Apolo3 pull request #5
Opened 2021-07-02 15:37 UTC by LPacione

- Implementamos los patrones Broker y Proxy. El Broker como intermediario que localiza los servicios de interes; y cada Proxy como el intermediario entre Broker y su servicio correspondiente.
- Por otro lado, hicimos las modificaciones necesarias en el repositorio para poder adaptarnos a otros servicios externos.
- Por ultimo, modificamos la vista para que el usuario pueda seleccionar, entre las fuentes disponibles, cada articulo individualmente

2021-07-02 22:12 UTC, elagarrigue requested changes
Diagrama:
- Agregar los proxies concretos, ya que no es 1 a 1 como otras interfaces - implementaciones
- Que cada proxy concreto tenga la referencia directa a la librería externa, para que quede clara la estructura

2021-07-02 22:12 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/view/MoreDetailsView.kt
> +    private var indexSpinner = 0
Mover al ui state

2021-07-02 22:12 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/view/MoreDetailsView.kt
> +        }
```suggestion
        val spinnerNamess: MutableList<String> = mutableListOf().addAll(listOfCards.map { it.source.service }  )
```

2021-07-02 22:12 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/view/MoreDetailsView.kt
> +        openExternalUrl(uiStateService.cards[indexSpinner].infoURL)
Crear un método `uiStateService.getCurrentCard()`

2021-07-02 22:12 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/view/MoreDetailsView.kt
> +            loadLastImage()
loadServiceImage

2021-07-02 22:12 UTC, elagarrigue commented on AK Apolo/app/build.gradle
> +    }
No se utiliza, revertir

2021-07-02 22:12 UTC, elagarrigue commented on AK Apolo/app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
No se utilizan, revertir

2021-07-02 22:58 UTC, SaintRoguer commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/view/MoreDetailsView.kt
> +        }
El metodo addAll() devuelve un boolean por lo que es necesario hacer en dos lineas de la siguiente manera: 
val spinnerNames: MutableList<String> = mutableListOf()
spinnerNames.addAll(listOfCards.map { it.source.service })

2021-07-05 18:08 UTC, elagarrigue reviewed
Sólo les falta el asterisco en el diagrama, para indicar que el broker depende de una lista de proxies

2021-07-06 13:49 UTC, elagarrigue requested changes
-Mientras se traen los datos en more details se puede apretar "view full article" y genera un crash. 
-Un progress bar para indicar loading estaría bien

2021-07-08 13:14 UTC, elagarrigue requested changes
Últimos cambios:
- Un comentario menor sobre el progress bar
- El broker les quedó en `local`,  debería estar en `external`. Recuerden actualizar el diagrama

2021-07-08 13:35 UTC, LPacione commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/view/MoreDetailsView.kt
> +        progressBar.isVisible = uiStateService.actionsEnabled
Hola Emma, con un solo metodo con la forma en que nos recomendas no nos funciona, por eso optamos por hacer dos metodos por separado. En el caso de buscar una cancion y cortar internet antes de apretar "More Details", podemos ver como queda
![imagen](https://user-images.githubusercontent.com/42450877/124930761-fd907e80-dfd7-11eb-9f55-fa23e367fc67.png)
Igualmente probamos con tu recomendacion, pero no hubo exito.

2021-07-08 13:59 UTC, elagarrigue commented on AK Apolo/app/src/main/java/ayds/apolo/songinfo/moredetails/view/MoreDetailsView.kt
> +        progressBar.isVisible = uiStateService.actionsEnabled
Ah bien, no lo probé si resultados, claro. No hay problema, déjenlo así. En general, es mejor usar alguna terminología general "show loading / hide loading", pensando en más casos donde se prenda/apague el loading. Pero en este caso no hace falta.

2021-07-08 14:01 UTC, elagarrigue approved these changes

2021-07-08 14:01 UTC, elagarrigue commented
🙌🏽

2021-07-08 14:01 UTC, merged